apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml

namespace: prod

# In production, recommend using SealedSecrets or ExternalSecrets
secretGenerator:
  - name: app-secrets
    literals:
      - DB_NAME=auraweb_db
      - DB_USER=admin
      - DB_PASSWORD=CHANGE_THIS_IN_PROD
      - JWT_SECRET=CHANGE_THIS_IN_PROD
      - JWT_REFRESH_SECRET=CHANGE_THIS_IN_PROD
